name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Cambia esto por la rama que uses para producción, normalmente 'main' o 'master'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Upload dist as artifact (optional, if you want to keep the build result)
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          # Artifact name
          name: dist
          # Path of the directory containing the static assets.
          path: dist
          
      
        
